version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install 
      - npm install -g @nestjs/cli
      - npm install -save @types/express
      - npm install -save @types/express-serve-static-core
      - npm install -save @types/multer

  build:
    commands:
      - echo "Building NestJS application..."
      - npm run build

  post_build:
    commands:
      - echo "Running database migration..."
      - npm run migration:run 
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*' 
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*' 