version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install 
      - npm install -g @nestjs/cli

  pre_build:
    commands:
      - echo "Running database migration..."
      - npm run migration:run 
      - echo "Build completed successfully!"

  build:
    commands:
      - echo "Building NestJS application..."
      - npm run build

artifacts:
  files:
    - '**/*' 
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*' 